name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        distribution: ['ubuntu-latest', 'ubuntu-20.04']

    steps:
      - uses: actions/checkout@v3

      - name: Set up test environment
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck bats

      - name: Run shellcheck
        run: |
          shellcheck install.sh
          find lib tests -type f -name "*.sh" -exec shellcheck {} +

      - name: Run tests
        run: |
          make test

      - name: Test installation (simulation mode)
        run: |
          ./install.sh --simulate

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run super-linter
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_BASH: true
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true

  coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Install kcov
        run: |
          sudo apt-get update
          sudo apt-get install -y kcov

      - name: Generate coverage report
        run: make coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/coverage.xml
